import React from 'react'
import NavBar from '../components/NavBar'
import { motion } from 'framer-motion'

const Create = ({ textColor, secondaryTextColor, backgroundColor, primaryColor }) => {
  return (
    <motion.div initial={{x: "-100%"}} animate={{x: "0"}} exit={{x: "-100%"}}>
      <NavBar textColor={textColor} secondaryTextColor={secondaryTextColor} backgroundColor={backgroundColor} primaryColor={primaryColor} />
      <h1 className='text-center py-[20px] text-[1.6em] font-bold'>Welcome to AGallery or APhotos!</h1>
      <p className='p-[25px]'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deleniti est accusantium consequatur hic optio pariatur repellat sequi facere inventore sit? Dignissimos quidem recusandae soluta. Repellendus culpa dolores dolorem impedit. Velit voluptatum totam quas eaque ipsum cupiditate architecto ipsam, maxime inventore consectetur repellat in perspiciatis, perferendis aperiam tenetur itaque, ea eos tempore est at facilis ratione soluta! Pariatur fugiat incidunt tempora nulla minima facilis hic sequi optio, quisquam fuga laudantium vel assumenda quasi tenetur tempore voluptatum facere. Eum voluptate ea, iure consequatur dicta quidem? Magni molestiae dolore odit corporis voluptatibus officiis accusamus illo quo minima rerum. Explicabo distinctio asperiores obcaecati officiis et neque quibusdam ratione ipsa rerum nesciunt alias doloremque minima unde facere nisi inventore, consequatur mollitia commodi? Soluta, in. Nemo iure aliquid et quos perspiciatis. Beatae reprehenderit nisi, illum, at vel voluptates magnam deserunt eaque sit sequi fugiat ipsa est quod quos facilis dolore error vero quibusdam libero! Repellat eius, aperiam, excepturi fuga tenetur, iure dolore optio omnis earum assumenda vitae voluptate dolores tempora nostrum! Laboriosam impedit vero quas sequi excepturi tenetur exercitationem saepe asperiores praesentium quibusdam quia expedita odit sit nesciunt quaerat, doloremque commodi possimus laudantium dolorem nihil, nam repellendus aperiam. Omnis maxime, obcaecati recusandae aspernatur beatae neque! Ex voluptates cum expedita atque beatae nobis recusandae voluptatem excepturi adipisci repellat mollitia possimus, a rerum quam dignissimos iure eius. Ipsa est nihil vero officia aspernatur explicabo accusantium dolorum consequatur pariatur, quaerat debitis provident minima a reiciendis ipsam harum ut iste illo aut quae ex omnis, natus tenetur consequuntur! Repellendus nesciunt magnam omnis, odit expedita sunt temporibus dolorem, enim deleniti numquam quas reprehenderit pariatur obcaecati voluptatum officia tenetur similique animi officiis nam quibusdam veritatis voluptate? Voluptatum ducimus amet earum rem corrupti laborum voluptates sint, fugit ipsa facere quidem quaerat id labore dolorum distinctio ad tempore, hic minus? Quaerat culpa, quia deserunt molestias, nihil vitae nam quos asperiores, harum corrupti assumenda qui fugiat obcaecati quam ipsum suscipit explicabo quas doloremque error enim voluptate sit maiores veniam eius! </p>
      <h1 className='text-[1.6rem] font-bold mx-[20px]'>Mega App Information</h1>
      <p className='p-[20px]'>Officia accusantium nulla, impedit ex voluptates cupiditate dolores doloremque quia dignissimos nobis enim dolore tempore repellat quis nemo quaerat consequuntur explicabo perferendis, eos rem debitis laboriosam a! Asperiores quae dolore, voluptatem voluptatibus veritatis accusamus totam sapiente, ipsam corporis magnam alias ullam ducimus inventore? Perspiciatis in, aut ex doloremque ullam dicta fuga praesentium tenetur vel odio, possimus, odit tempora! Saepe assumenda error, id non doloribus exercitationem minus voluptatem! At aperiam unde blanditiis natus eaque! Tempora distinctio ullam perferendis aperiam quis natus minima, ex ab! Eligendi, debitis asperiores praesentium perspiciatis consectetur vero inventore. Dignissimos illo magni, similique libero in numquam tenetur laudantium pariatur doloribus accusamus dolorem fugit saepe, optio molestiae quas. Aliquid architecto officia ut veritatis! Magnam maiores illo neque natus, architecto quisquam esse in ullam ducimus illum earum? Ratione maxime atque dolor velit quae aperiam, quam dolore? Dicta, deleniti sed? Eaque repudiandae eum, iste deleniti velit magnam! Dolor laudantium provident corporis voluptatibus harum labore. Aliquam optio ipsam id dolores. Expedita a ratione recusandae enim, cumque harum. Modi enim dolorum exercitationem, incidunt illum cupiditate consequuntur soluta similique.</p>
      <h1 className='text-[1.6rem] font-bold mx-[20px]'>Antonyan Apps and Eric Antonyan</h1>
      <p className='p-[20px]'>Officia accusantium nulla, impedit ex voluptates cupiditate dolores doloremque quia dignissimos nobis enim dolore tempore repellat quis nemo quaerat consequuntur explicabo perferendis, eos rem debitis laboriosam a! Asperiores quae dolore, voluptatem voluptatibus veritatis accusamus totam sapiente, ipsam corporis magnam alias ullam ducimus inventore? Perspiciatis in, aut ex doloremque ullam dicta fuga praesentium tenetur vel odio, possimus, odit tempora! Saepe assumenda error, id non doloribus exercitationem minus voluptatem! At aperiam unde blanditiis natus eaque! Tempora distinctio ullam perferendis aperiam quis natus minima, ex ab! Eligendi, debitis asperiores praesentium perspiciatis consectetur vero inventore. Dignissimos illo magni, similique libero in numquam tenetur laudantium pariatur doloribus accusamus dolorem fugit saepe, optio molestiae quas. Aliquid architecto officia ut veritatis! Magnam maiores illo neque natus, architecto quisquam esse in ullam ducimus illum earum? Ratione maxime atque dolor velit quae aperiam, quam dolore? Dicta, deleniti sed? Eaque repudiandae eum, iste deleniti velit magnam! Dolor laudantium provident corporis voluptatibus harum labore. Aliquam optio ipsam id dolores. Expedita a ratione recusandae enim, cumque harum. Modi enim dolorum exercitationem, incidunt illum cupiditate consequuntur soluta similique.</p>
    </motion.div>
  )
}

export default Create